<template>
  <ConfirmationModal
    :classes="{
      'w-full mx-4 sm:mx-0 sm:w-3/4 lg:w-1/2 xl:w-1/3 2xl:w-1/3 min-h-[500px]': !user,
    }"
    @on-close="closeModal"
  >
    <template #modal-header>
      {{ editMode ? $t("Edit User") : $t("Create User") }}
    </template>

    <template #modal-body>
      <Form ref="userForm" @submit="onSubmit">
        <StepperRoot
          v-if="!user"
          v-model="step"
          class="-mx-4 -mt-4 flex rounded-md bg-gray-100 p-4"
        >
          <StepperItem
            v-for="item in steps"
            :key="item.value"
            :step="item.step"
            :disabled="step < item.step"
            class="group relative flex w-full cursor-pointer flex-col items-center"
          >
            <StepperTrigger
              class="inline-flex size-10 shrink-0 items-center justify-center rounded-full border-2 border-theme-200 bg-theme-200 text-white shadow-sm outline outline-2 outline-transparent focus:outline-theme-500 group-data-[disabled]:cursor-not-allowed group-data-[state=inactive]:border-gray-200 group-data-[state=inactive]:bg-white group-data-[state=completed]:text-white group-data-[state=inactive]:text-gray-700 group-data-[disabled]:opacity-50"
              :class="{ '!outline-theme-500 focus:!outline-theme-800': step === item.step }"
            >
              <StepperIndicator>
                <font-awesome-icon :icon="item.icon" class="size-4" />
              </StepperIndicator>
            </StepperTrigger>

            <StepperSeparator
              v-if="item.step !== steps[steps.length - 1].step"
              class="absolute left-[calc(50%+20px)] right-[calc(-50%+20px)] top-5 block h-0.5 shrink-0 rounded-full bg-gray-300/50"
              :class="{ 'bg-theme-200': step > item.step }"
            />
          </StepperItem>
        </StepperRoot>

        <div v-if="!user" class="-mx-4 bg-gray-50 p-4 px-8">
          <h1 class="max-w-sm text-pretty text-xl font-medium text-gray-700">
            {{ step + ". " + steps[step - 1].title }}
          </h1>
          <p class="max-w-sm text-pretty text-sm text-gray-700">
            {{ steps[step - 1].description }}
          </p>
        </div>
        <div :class="{ 'relative grow p-4 px-0': !user }">
          <TransitionGroup name="fade">
            <UserAccountForm
              v-show="tab === 'account'"
              :user="user ?? account"
              @form-data-change="updateAccountData"
            />

            <UserContextsForm
              v-show="tab === 'contexts'"
              :user="user ?? account"
              @change="updateContexts"
            />

            <UserRoleList
              v-show="tab === 'roles'"
              :user="user ?? account"
              @roles-changed="updateSelectedRoles"
            />

            <UserTeamsForm
              v-show="tab === 'teams'"
              :user="user ?? account"
              @teams-updated="updateTeams"
            />

            <UserAddressForm
              v-show="tab === 'address'"
              :full-name-of-user="userFullName"
              @form-data-change="updateAddressData"
            />
          </TransitionGroup>
        </div>
      </Form>
    </template>

    <template #confirm-button>
      <ModalButton
        v-if="step === steps[steps.length - 1].step && !user"
        variant="success"
        @click="submitUserForm"
      >
        {{ editMode ? $t("Edit User") : $t("Create User") }}
      </ModalButton>
      <ModalButton v-else-if="!user" variant="theme" @click="nextStep">
        {{ $t("Next") }}
      </ModalButton>
      <ModalButton v-else variant="theme" @click="updateUser">
        {{ $t("Update User") }}
      </ModalButton>
    </template>
  </ConfirmationModal>
</template>

<script setup>
import {
  StepperIndicator,
  StepperItem,
  StepperRoot,
  StepperSeparator,
  StepperTrigger,
} from "reka-ui";

const props = defineProps({
  user: {
    type: Object,
    default: () => null,
  },
  isCreatingCustomer: {
    type: Boolean,
    default: false,
  },
});

const emit = defineEmits(["create-user", "update-user", "close-modal"]);

const { t: $t } = useI18n();

const userForm = ref(null);
const address = ref({
  address: "",
  number: "",
  zip_code: "",
  city: "",
  region: "",
  country: "",
  is_business_user: false,
  full_name: "",
  company_name: "No Company",
  tax_nr: "",
  phone_number: "",
});
const account = ref({
  email: "",
  profile: { first_name: "", last_name: "", gender: "other" },
  roles: [],
  ctx: [props.isCreatingCustomer ? 2 : 1],
  teams: [],
});

const steps = [
  {
    step: 1,
    title: $t("Account"),
    tab: "account",

    description: $t(
      "The minimum required information to create a user. The password of the user will be generated by us and send to their e-mail.",
    ),
    icon: ["fas", "user"],
  },
  {
    step: 2,
    title: $t("Contexts"),
    tab: "contexts",

    description: !props.isCreatingCustomer
      ? $t(
          "The user's context determines at a high level their access to your storefront or manager. Where 'MGR' stands for the manager you're currently working in and 'WEB' for your storefront.",
        )
      : $t(
          "Customers initally always have the 'WEB' context ensuring they only have access to your webshop. You can change their contexts later at their profile.",
        ),
    icon: ["fas", "users"],
  },
  {
    step: 3,
    title: $t("Roles"),
    tab: "roles",

    description: $t(
      "These self-managed roles can be used to manage the user's access and permissions to the system. You can manage these roles under 'roles and rights' at the 'manage' menu.",
    ),
    icon: ["fas", "tag"],
  },
  {
    step: 4,
    title: $t("Teams"),
    tab: "teams",

    description: $t(
      "Teams are a way to group users together and share data between them. Teams can also be used to manage the user's access to media sources.",
    ),
    icon: ["fas", "users"],
  },
  {
    step: 5,
    title: $t("Address"),
    tab: "address",

    description: $t(
      "Last but not least, create a new address or select an existing one to assign to this user.",
    ),
    icon: ["fas", "house"],
  },
];
const step = ref(steps[0].step);
const tab = computed(() => steps.find((s) => s.step === step.value)?.tab);

const editMode = computed(() => props.user !== null);

const userFullName = computed(() => {
  if (account.value.first_name && account.value.last_name) {
    return `${account.value.first_name} ${account.value.last_name}`;
  }
  return "";
});

const updateSelectedRoles = (roles) => {
  if (editMode.value) {
    account.value.roles = roles.map((role) => role.id);
  } else {
    account.value.roles = roles.map((role) => role.name);
  }
};

const updateAccountData = (accountData) => {
  account.value.email = accountData.email;
  account.value.profile.first_name = accountData.first_name;
  account.value.profile.last_name = accountData.last_name;
  account.value.profile.gender = accountData.gender;
};

const updateAddressData = (addressData) => {
  address.value = addressData;
};

const updateContexts = (contexts) => {
  account.value.ctx = contexts;
};

const updateTeams = (teams) => {
  account.value.teams = teams;
};

const constructAddress = () => {
  // TODO: Add Validation
  return {
    address: address.value.street,
    number: address.value.houseNumber,
    city: address.value.city,
    region: address.value.region,
    zip_code: address.value.zipCode,
    country_id: address.value.countryId,
    type: address.value.addressType,
    full_name: address.value.fullName,
    company_name: `${address.value.companyName ? address.value.companyName : ""}`,
    phone_number: `${address.value.phoneNumber ? address.value.phoneNumber : ""}`,
    tax_nr: `${address.value.vatNumber ? address.value.vatNumber : ""}`,
    default: true,
  };
};

const createUser = () => {
  const user = {
    ...account.value,
    sendpassword: true,
    email: account.value.email,
    roles: account.value.roles,
    ctx: account.value.ctx,
    teams: account.value.teams,
  };
  const addressData = constructAddress();
  emit("create-user", { user, address: addressData });
};

const updateUser = () => {
  const user = {
    email: account.value.email,
    roles: account.value.roles,
  };
  const profile = {
    first_name: account.value.profile.first_name,
    last_name: account.value.profile.last_name,
    gender: account.value.profile.gender,
  };
  emit("update-user", { user, profile });
};

const closeModal = () => {
  emit("close-modal");
};

const submitUserForm = () => {
  userForm.value.$el.requestSubmit();
};

const onSubmit = () => {
  if (editMode.value) {
    updateUser();
  } else {
    createUser();
  }
};

async function nextStep() {
  const { valid } = await userForm.value.validate();
  if (valid) step.value++;
}
</script>

<style lang="scss" scoped>
.heading {
  @apply mb-2 font-bold uppercase tracking-wide;
}
</style>
