<?php

declare(strict_types=1);

namespace App\Listeners\Tenant;

use App\Events\Tenant\PasswordChangedEvent;
use App\Mail\Tenant\Auth\PasswordChangedMail;
use App\Models\Tenants\Member;
use App\Models\Tenants\User;
use Illuminate\Contracts\Events\Dispatcher;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Facades\Mail;
use LogicException;

final class PasswordChangedListener implements ShouldQueue
{
    use InteractsWithQueue;

    /**
     * Notify in case of password is generated by the system
     *
     * @param PasswordChangedEvent $event
     *
     * @return void
     */
    public function onPasswordChangedNotifyAuthenticatable(
        PasswordChangedEvent $event
    ): void
    {
        if (!$event->authenticatable instanceof User && !$event->authenticatable instanceof Member) {
            throw new LogicException(
                sprintf(
                    'Given authenticatable object "%s" is not supported. Allowed are only (User & Member)',
                    get_class($event->authenticatable)
                )
            );
        }

        Mail::to(
            $event->authenticatable->getAttribute('email')
        )->send(
            new PasswordChangedMail(
                newPasswordPlain: $event->shouldNewPasswordMasked ?
                    str_repeat('*', 8) : $event->newPasswordPlain,
                authenticatable: $event->authenticatable,
                tenant: $event->tenant,
                actor: $event->actor
            )
        ) ?: throw new LogicException('Could not send the email');
    }

    /**
     * @param Dispatcher $dispatcher
     *
     * @return void
     */
    public function subscribe(
        Dispatcher $dispatcher
    ): void
    {
        $dispatcher->listen(PasswordChangedEvent::class, [$this, 'onPasswordChangedNotifyAuthenticatable']);
    }
}
