<?php

namespace Database\Seeders\Tenants;

use App\Models\Tenant\Area;
use App\Models\Tenant\Npace;
use App\Models\Tenant\Setting;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{

    /**
     * Run the database seeders.
     *
     * @return void
     */
    public function run()
    {
        $settings = [
            /**
             * core - language
             */
            [
                "name" => "Default Locale",
                "description" => "",
                "key" => "manager_language",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "EN||NL||AR||ES||DE",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "core",
                "area" => "language",
                "lexicon" => null,
                "value" => "EN",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            /**
             * core - currency
             */
            [
                "name" => "Currency",
                "description" => "",
                "key" => "currency",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'USD||EUR||GBP||JPY||AUD||CAD||CHF||CNY||SEK||NZD||MXN||SGD||HKD||NOK||KRW||TRY||RUB||INR||BRL||ZAR||PLN||PHP||CZK||MYR||IDR||HUF||ILS||THB||AED||SAR||QAR||EGP||VND||BDT||PKR||KWD||BHD||OMR||JOD||CLP||COP||PEN||ARS||UYU||RON||BGN||HRK||DKK||ISK',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "core",
                "area" => "currency",
                "lexicon" => null,
                "value" => "USD",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Time Zone",
                "description" => "",
                "key" => "time_zone",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "time_zone",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "core",
                "area" => "currency",
                "lexicon" => null,
                "value" => "UTC",
                "ctx_id" => 1,
                "data_model" => "local"
            ],
            /**
             * core - mail
             */
            [
                "name" => "Mail Charset",
                "description" => "MAil host like smtp.mailtrap.io",
                "key" => "mail_charset",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "UTF-8||UTF-16||UTF-32",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => "UTF-8",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail Encoding",
                "description" => "8bit",
                "key" => "mail_encoding",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "8bit||16bit||32bit",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => "8bit",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "SMTP Hosts",
                "description" => "MAil host like smtp.mailtrap.io",
                "key" => "mail_smtp_hosts",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => "smtp-relay.sendinblue.com",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail Port",
                "description" => "Mail port like 2525",
                "key" => "mail_smtp_port",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => 587,
                "ctx_id" => 1,
                "data_model" => "database"

            ],
            [
                "name" => "Mail Username",
                "description" => "Mail Username like jone,doe",
                "key" => "mail_smtp_user",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => "smtp-relay@prindustry.nl",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail Password",
                "description" => "Mail Password",
                "key" => "mail_smtp_pass",
                "data_type" => "string",
                "secure_variable" => true,
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => "",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail Encryption",
                "description" => "Mail Encryption",
                "key" => "mail_smtp_prefix",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => "tls",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "From Address",
                "description" => "Mail From Address",
                "key" => "mail_smtp_from",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => "noreply@prindustry.nl",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "From Name",
                "description" => "Mail From Name",
                "key" => "mail_smtp_from_name",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => "Prindustry",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Use SMTP",
                "description" => "Mail Use SMTP",
                "key" => "mail_use_smtp",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "mail",
                "lexicon" => null,
                "value" => true,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            /**
             * mail colors
             */
            [
                "name" => "Mail background colors",
                "description" => "This determines the mail background colors.",
                "key" => "mail_bg_color",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#edf2f7',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail button Primary colors",
                "description" => "This determines the color Primary of the whole e-mail.",
                "key" => "mail_button_primary_colors",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#2f94b3',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail button Secondary colors",
                "description" => "This determines the color Secondary of the whole e-mail.",
                "key" => "mail_button_secondary_colors",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#333333',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail button primary text colors",
                "description" => "This determines the Primary button text color the e-mail.",
                "key" => "mail_text_button_primary_colors",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#ffffff',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail button Secondary text colors",
                "description" => "This determines the Secondary button text color the e-mail.",
                "key" => "mail_text_button_secondary_colors",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#ffffff',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            /** mail font  */
            [
                "name" => "Mail fonts family",
                "description" => "This determines the styling of the text of the whole email.",
                "key" => "mail_fonts_family",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'Arial||Helvetica||Verdana||Tahoma||Trebuchet MS||Gill Sans||Segoe UI||Geneva||Lucida Sans Unicode||Lucida Grande||Impact||Times New Roman||Georgia||Palatino Linotype||Book Antiqua||Courier New||Lucida Console||Monaco||Consolas||Cambria',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'Arial',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail fonts color",
                "description" => "This determines the styling of the text of the whole email.",
                "key" => "mail_fonts_color",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => '',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#718096',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail fonts size",
                "description" => "This determines the font size of the whole email.",
                "key" => "mail_fonts_size",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => '10px||11px||12px||13px||14px||15px||16px||18px||20px||24px',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '16px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            /** Mail button border and padding  */
            [
                "name" => "Mail button alignment",
                "description" => "This determines the button alignment style of the whole email.",
                "key" => "mail_button_alignment",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'center||left||right',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => "left",
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail button border",
                "description" => "This determines the button border style of the whole email.",
                "key" => "mail_button_border_radius",
                "secure_variable" => false,
                "data_type" => "objects",
                "data_variable" => 'bt:0px,bb:0px,br:0px,bl:0px',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => "bt:3px,bb:3px,br:3px,bl:3px",
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail button padding",
                "description" => "This determines the button padding of the whole email.",
                "key" => "mail_button_padding",
                "secure_variable" => false,
                "data_type" => "objects",
                "data_variable" => 'pt:0px,pb:0px,pr:0px,pl:0px',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'pt:5px,pb:5px,pr:12px,pl:12px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            /**
             * Mail content
             */
            [
                "name" => "Mail content card width",
                "description" => "These mail content width.",
                "key" => "mail_content_width",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '600px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail content card background color ",
                "description" => "The mail content background color.",
                "key" => "mail_content_bg_color",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#ffffff',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail content card border width ",
                "description" => "The mail content color width.",
                "key" => "mail_content_b_width",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '0px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail content card border color ",
                "description" => "The mail content border color.",
                "key" => "mail_content_b_color",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#000000',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail content card border radius ",
                "description" => "The mail content border radius.",
                "key" => "mail_content_b_radius",
                "secure_variable" => false,
                "data_type" => "objects",
                "data_variable" => 'tr:0px,tl:0px,br:0px,bl:0px',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'tr:3px,tl:3px,br:3px,bl:3px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail content card padding ",
                "description" => "The mail content border radius.",
                "key" => "mail_content_padding",
                "secure_variable" => false,
                "data_type" => "objects",
                "data_variable" => 'pt:0px,pb:0px,pr:0px,pl:0px',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'pt:32px,pb:32px,pr:32px,pl:32px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail content alignment ",
                "description" => "The mail content alignment.",
                "key" => "mail_content_alignment",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'center||left||right',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'left',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail content card alignment ",
                "description" => "The mail content card alignment.",
                "key" => "mail_content_card_alignment",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'center||left||right',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'center',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            /**
             * mail footer settings
             */
            [
                "name" => "Mail footer content alignment",
                "description" => "The mail footer content alignment.",
                "key" => "mail_footer_alignment",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'center||left||right',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'right',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail footer content background colors",
                "description" => "The mail footer content background colors.",
                "key" => "mail_footer_bg_color",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#edf2f7',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail footer fonts family",
                "description" => "This determines the styling of the text footer of the email.",
                "key" => "mail_footer_fonts_family",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'Arial||Helvetica||Verdana||Tahoma||Trebuchet MS||Gill Sans||Segoe UI||Geneva||Lucida Sans Unicode||Lucida Grande||Impact||Times New Roman||Georgia||Palatino Linotype||Book Antiqua||Courier New||Lucida Console||Monaco||Consolas||Cambria',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'Arial',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail footer fonts color",
                "description" => "This determines the styling of the footer text of the email.",
                "key" => "mail_footer_fonts_color",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => '',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#b0adc5',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail footer fonts size",
                "description" => "This determines the font size footer of the email.",
                "key" => "mail_footer_fonts_size",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => '10px||11px||12px||13px||14px||15px||16px||18px||20px||24px',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '14px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail footer padding",
                "description" => "This determines the footer padding.",
                "key" => "mail_footer_padding",
                "secure_variable" => false,
                "data_type" => "objects",
                "data_variable" => 'pt:0px,pb:0px,pr:0px,pl:0px',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'pt:24px,pb:24px,pr:0px,pl:0px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            /**
             * mail header settings
             */

            [
                "name" => "Mail header content alignment",
                "description" => "The mail header content alignment.",
                "key" => "mail_header_alignment",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'center||left||right',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'center',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail header content background colors",
                "description" => "The mail header content background colors.",
                "key" => "mail_header_bg_color",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '#edf2f7',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail header padding",
                "description" => "This determines the header padding.",
                "key" => "mail_header_padding",
                "secure_variable" => false,
                "data_type" => "objects",
                "data_variable" => 'pt:0px,pb:0px,pr:0px,pl:0px',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'pt:24px,pb:24px,pr:0px,pl:0px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            /**
             * Mail logo
             */
            [
                "name" => "Mail logo",
                "description" => "Mail logo",
                "key" => "mail_logo",
                "secure_variable" => false,
                "data_type" => "image",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1,
                "data_model" => "database"
            ],


            [
                "name" => "Mail logo position",
                "description" => "The default logo should be the Tenant Company Logo set in Tenant Settings.",
                "key" => "mail_logo_position",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'header||content||footer',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'header',
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Mail align logo position",
                "description" => "The default logo should be the Tenant Company Logo set in Tenant Settings.",
                "key" => "mail_align_logo",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => 'left||center||right',
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => 'center',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            [
                "name" => "Mail logo width",
                "description" => "The logo width in px.",
                "key" => "mail_logo_width",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "themes",
                "area" => "mail",
                "lexicon" => null,
                "value" => '150px',
                "ctx_id" => 1,
                "data_model" => "database"
            ],

            /**
             * core - taxes
             */
            [
                "name" => "Vies tax number check",
                "description" => "Vies tax number check",
                "key" => "vies_tax_nr_check",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "taxes",
                "lexicon" => null,
                "value" => true,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Vat",
                "description" => "Vat",
                "key" => "vat",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "core",
                "area" => "taxes",
                "lexicon" => null,
                "value" => 0,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            /**
             * Orders - order
             */
            [
                "name" => "Order number pattern",
                "description" => "How many digits will be used in your order number",
                "key" => "order_number_pattern",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "2||4||6||8||10||12",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "order",
                "lexicon" => null,
                "value" => 4,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Order number start from",
                "description" => "From where will the order number start",
                "key" => "order_start_number",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "order",
                "lexicon" => null,
                "value" => 1,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Receive orders files through",
                "description" => "How do like to receive orders files",
                "key" => "supplier_receive_through",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "xml||ftp||mail",
                "multi_select" => true,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "external",
                "lexicon" => null,
                "value" => ["mail,ftp"],
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            /**
             * automation
             */
            [
                "name" => "Order flow control",
                "description" => "Enable Order flow control",
                "key" => "enable_order_flow_control",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "automation",
                "lexicon" => null,
                "value" => false,
                "ctx_id" => 1
            ],
            [
                "name" => "Collect external order by type",
                "description" => "Collect external order by type ",
                "key" => "collect_external_order_by_type",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "order||item||supplier",
                "multi_select" => true,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "external",
                "lexicon" => null,
                "value" => ["order"],
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            /**
             * Orders - quotation
             */
            [
                "name" => "Quotation expiry date",
                "description" => "Select the amount of days after which a quotation will expire",
                "key" => "quotation_expires_after",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "5||10||15||30||60",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => 15,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation logo",
                "description" => "Quotation logo (max 300 x 300)px",
                "key" => "quotation_logo",
                "secure_variable" => false,
                "data_type" => "image",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation logo document width",
                "description" => "Set the logo to the full width of the document.",
                "key" => "quotation_logo_full_document_width",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => false,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation logo position",
                "description" => "Quotation logo position",
                "key" => "quotation_logo_position",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "left||right||center",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => "left",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation logo width",
                "description" => "Quotation logo width",
                "key" => "quotation_logo_width",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => "min:0||max:500",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => 300,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation customer address position direction",
                "description" => "Quotation customer address position direction",
                "key" => "quotation_customer_address_position_direction",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "rtl||ltr",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => "ltr",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation customer address position",
                "description" => "Quotation customer address position",
                "key" => "quotation_customer_address_position",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => "min:0||max:1000",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => 30,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation font",
                "description" => "Quotation font",
                "key" => "quotation_font",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "Lucida Grande||Arial||Helvetica||Verdana",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => "Helvetica",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation font size",
                "description" => "Quotation font size in pt",
                "key" => "quotation_font_size",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => "min:1||max:14",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => 9,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation background",
                "description" => "Quotation background",
                "key" => "quotation_background",
                "secure_variable" => false,
                "data_type" => "image",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation on own letterhead",
                "description" => "Quotation on own letterhead",
                "key" => "quotation_own_letterhead",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => false,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation payment QR code",
                "description" => "Quotation payment QR code",
                "key" => "quotation_qr_code",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => false,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Quotation letterhead size",
                "description" => "Quotation letterhead size",
                "key" => "quotation_letterhead_size",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "A4||Letter(USA)",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "quotation",
                "lexicon" => null,
                "value" => "A4",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            /**
             * Orders - invoice
             */
            [
                "name" => "Invoice ID number pattern",
                "description" => "Invoice number pattern e.g. {year-4-digit}",
                "key" => "invoice_number_pattern",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "year-4-digit||year-2-digit||month-number||customer-id",
                "multi_select" => true,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => ["year-4-digit"],
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Restart yearly the invoice id",
                "description" => "Restart yearly the invoice id based on the year e.g. 2022-1 / 2023-1",
                "key" => "restart_invoice_id",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => true,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice number id length",
                "description" => "How many digits will be used in your invoice number",
                "key" => "invoice_number_id_length",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "2||4||6||8||10||12",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => 4,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice number start from",
                "description" => "From where will the invoice number start",
                "key" => "invoice_start_number",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => 1,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice logo",
                "description" => "Invoice logo (max 300 x 300)px",
                "key" => "invoice_logo",
                "secure_variable" => false,
                "data_type" => "image",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice logo document width",
                "description" => "Set the logo to the full width of the document.",
                "key" => "invoice_logo_full_document_width",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => false,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice logo position",
                "description" => "Invoice logo position",
                "key" => "invoice_logo_position",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "left||right||center",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => "left",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice logo width",
                "description" => "Invoice logo width",
                "key" => "invoice_logo_width",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => "min:0||max:500",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => 300,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice customer address position direction",
                "description" => "Invoice customer address position direction",
                "key" => "invoice_customer_address_position_direction",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "rtl||ltr",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => "ltr",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice customer address position",
                "description" => "Invoice customer address position",
                "key" => "invoice_customer_address_position",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => "min:0||max:1000",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => 30,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice font",
                "description" => "Invoice font",
                "key" => "invoice_font",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "Lucida Grande||Arial||Helvetica||Verdana",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => "Helvetica",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice font size",
                "description" => "Invoice font size in pt",
                "key" => "invoice_font_size",
                "secure_variable" => false,
                "data_type" => "integer",
                "data_variable" => "min:1||max:14",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => 9,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice background",
                "description" => "Invoice background",
                "key" => "invoice_background",
                "secure_variable" => false,
                "data_type" => "image",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice on own letterhead",
                "description" => "Invoice on own letterhead",
                "key" => "invoice_own_letterhead",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => false,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice payment QR code",
                "description" => "Invoice payment QR code",
                "key" => "invoice_qr_code",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => false,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Invoice letterhead size",
                "description" => "Invoice letterhead size",
                "key" => "invoice_letterhead_size",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "A4||Letter(USA)",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "invoice",
                "lexicon" => null,
                "value" => "A4",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Order Email To",
                "description" => "Order Email To",
                "key" => "order_email_to",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "mails",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Order Email CC",
                "description" => "Order Email CC",
                "key" => "order_email_cc",
                "secure_variable" => false,
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "orders",
                "area" => "mails",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            /**
             * campaigns - campaign
             */
            [
                "name" => "On campaign create default",
                "description" => "On campaign create default",
                "key" => "default_on_create",
                "secure_variable" => false,
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "campaigns",
                "area" => "campaign",
                "lexicon" => null,
                "value" => true,
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            /**
             * supplier settings
             */
            [
                "name" => "Supplier ftp connection type",
                "description" => "Ftp connection type where supplier can receive information, data on it.",
                "key" => "supplier_ftp_connection_type",
                "secure_variable" => false,
                "data_type" => "array",
                "data_variable" => "ftp||sftp",
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "ftp",
                "lexicon" => null,
                "value" => "sftp",
                "ctx_id" => 1,
                "data_model" => "database"
            ],
            [
                "name" => "Ftp host url",
                "description" => "Ftp connection host url/ip.",
                "key" => "supplier_ftp_connection_host",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "ftp",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "Ftp username",
                "description" => "Ftp connection username.",
                "key" => "supplier_ftp_connection_username",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => false,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "ftp",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "Ftp password",
                "description" => "Ftp connection password.",
                "key" => "supplier_ftp_connection_password",
                "secure_variable" => true,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "ftp",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "Ftp port",
                "description" => "Ftp connection port.",
                "key" => "supplier_ftp_connection_port",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "integer",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "ftp",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "Ftp path",
                "description" => "Ftp connection path to store data on it.",
                "key" => "supplier_ftp_connection_path",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "ftp",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "SMTP enabled",
                "description" => "smtp enable.",
                "key" => "supplier_mail_smtp",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => true,
                "ctx_id" => 1
            ],
            [
                "name" => "SMTP auth",
                "description" => "smtp auth.",
                "key" => "supplier_mail_smtp_auth",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => true,
                "ctx_id" => 1
            ],
            [
                "name" => "SMTP secure authentication",
                "description" => "smtp secure authentication",
                "key" => "supplier_mail_smtp_secure",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => true,
                "ctx_id" => 1
            ],
            [
                "name" => "SMTP host",
                "description" => "smtp host",
                "key" => "supplier_mail_smtp_host",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "SMTP port",
                "description" => "smtp port",
                "key" => "supplier_mail_smtp_port",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "integer",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => 587,
                "ctx_id" => 1
            ],
            [
                "name" => "SMTP from",
                "description" => "smtp from",
                "key" => "supplier_mail_from",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "SMTP username",
                "description" => "smtp username",
                "key" => "supplier_mail_username",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "SMTP password",
                "description" => "smtp password",
                "key" => "supplier_mail_password",
                "secure_variable" => true,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            [
                "name" => "Use team address",
                "description" => "Use team address",
                "key" => "use_team_address",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "boolean",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "checkout",
                "area" => "addresses",
                "lexicon" => null,
                "value" => true,
                "ctx_id" => 1
            ],

            /***
             * Remove this one after make company work with supplier
             */
            [
                "name" => "Supplier Email Address",
                "description" => "Send Order files to this e-mail",
                "key" => "supplier_mail_address",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "string",
                "data_variable" => null,
                "multi_select" => null,
                "incremental" => null,
                "namespace" => "supplier",
                "area" => "mail",
                "lexicon" => null,
                "value" => null,
                "ctx_id" => 1
            ],
            /**
             * Warehouses
             */
            [
                "name" => "Layout warehouse area",
                "description" => "Layout warehouse area",
                "key" => "layout_warehouse",
                "secure_variable" => false,
                "data_model" => "database",
                "data_type" => "array",
                "data_variable" => "hall||row||column||level",
                "multi_select" => true,
                "incremental" => null,
                "namespace" => "warehouse",
                "area" => "Layout",
                "lexicon" => null,
                "value" => ['row', 'column', 'level'],
                "ctx_id" => 1
            ]

        ];
        //Setting::query()->delete();
        collect($settings)->map(function ($setting) {
            $st = Setting::where('key', $setting['key'])->first();
            if($st) {
                $st->update(['data_variable' => $setting['data_variable']]);
            }else{
                Setting::create($setting);
            }

            $sysNamespace = \App\Models\Npace::firstOrCreate(['name' => $setting['namespace']]);
            $sysArea = \App\Models\Area::firstOrCreate(['name' => $setting['area']]);
            $sysNamespace->areas()->syncWithoutDetaching($sysArea);
            Npace::firstOrCreate(['name' => $setting['namespace']]);
            Area::firstOrCreate(['name' => $setting['area']]);
        });
    }
}
