// 1. Navigation Configuration (composables/useNavigationConfig.js)
export const navigationItems = [
  {
    name: "dashboard",
    icon: ["fal", "gauge-simple-max"],
    activeIcon: ["fad", "gauge-simple-max"],
    path: "/",
    permission: null,
    position: ["sidebar", "bottom"],
    disabled: false,
    routeMatch: (route) => route.path === "/",
  },
  {
    name: "marketplace",
    icon: ["fal", "sparkles"],
    activeIcon: ["fal", "sparkles"],
    path: "/marketplace/product-finder",
    permission: "finder.groups.moduleAccess",
    position: ["sidebar", "bottom"],
    disabled: false,
    beta: true,
    customIcon: "UIPrindustryBox",
    routeMatch: (route) => route.path.startsWith("/marketplace"),
    onClick: (store) => {
      store.commit("compare/set_compare_component", "CategoryOverview");
      store.commit("compare/set_flag", "compare");
    },
  },
  {
    name: "quotations",
    icon: ["fal", "file-signature"],
    activeIcon: ["fad", "file-signature"],
    path: "/quotations",
    permission: "quotations.groups.moduleAccess",
    position: ["sidebar", "bottom"],
    disabled: false,
    routeMatch: (route) => route.path.startsWith("/quotations"),
  },
  {
    name: "orders",
    icon: ["fal", "file-invoice-dollar"],
    activeIcon: ["fad", "file-invoice-dollar"],
    path: "/orders",
    permission: ["orders-access", "orders-list"],
    position: ["sidebar", "bottom"],
    disabled: false,
    routeMatch: (route) => route.path.startsWith("/orders"),
  },
  {
    name: "finances",
    icon: ["fal", "money-bill-trend-up"],
    activeIcon: ["fad", "money-bill-trend-up"],
    path: "/finances",
    permission: "transactions-access",
    position: ["sidebar"],
    disabled: false,
    routeMatch: (route) => route.path.startsWith("/finances"),
  },
  {
    name: "customers",
    icon: ["fal", "users"],
    activeIcon: ["fad", "users"],
    path: "/customers",
    permission: "members-access",
    position: ["sidebar", "bottom"],
    disabled: false,
    routeMatch: (route) => route.path.startsWith("/customers"),
  },
  {
    name: "assortment",
    icon: ["fal", "box-open-full"],
    activeIcon: ["fad", "box-open-full"],
    path: "/assortment",
    permission: "print-assortments.groups.moduleAccess",
    position: ["sidebar", "bottom"],
    disabled: false,
    routeMatch: (route) => route.path.startsWith("/assortment"),
  },
  {
    name: "cms",
    icon: ["fal", "window-restore"],
    activeIcon: ["fad", "window-restore"],
    path: "/cms",
    permission: "cms-access",
    position: ["sidebar", "bottom"],
    disabled: true,
    tooltip: "coming soon",
    routeMatch: (route) => route.path.startsWith("/cms"),
  },
  {
    name: "media",
    icon: ["fal", "photo-film"],
    activeIcon: ["fad", "photo-film"],
    path: "/filemanager",
    permission: "media-sources-access",
    position: ["sidebar", "bottom"],
    disabled: false,
    displayName: "media manager",
    routeMatch: (route) => route.path.startsWith("/filemanager"),
  },
  {
    name: "shop",
    icon: ["fal", "shop"],
    activeIcon: ["fad", "shop"],
    path: "/shop",
    permission: "shops-access",
    position: ["sidebar", "bottom"],
    disabled: false,
    routeMatch: (route) => route.path.startsWith("/shop"),
  },
  {
    name: "cart",
    icon: ["fal", "cart-shopping"],
    activeIcon: ["fad", "cart-shopping"],
    path: "/cart",
    permission: "cart-access",
    position: ["sidebar", "bottom"],
    disabled: false,
    routeMatch: (route) => route.path.startsWith("/cart"),
  },
];
