<template>
  <dialog
    ref="dialog"
    class="lg:max-w-[33%]] max-w-[90%] rounded-lg bg-white shadow-xl backdrop:bg-black/50 backdrop:backdrop-blur-sm dark:bg-gray-700 sm:max-w-[50%] 2xl:max-w-[25%]"
    @click="handleBackdropClick"
    @close="handleCancel"
  >
    <header
      class="sticky top-0 flex items-center justify-between gap-4 rounded-t-lg bg-gray-200 p-2 px-4 dark:bg-gray-800 dark:text-white"
    >
      <h2>{{ props.title }}</h2>
      <UIButton variant="neutral" :icon="['fad', 'xmark']" class="!h-5" @click="handleCancel" />
    </header>
    <main class="p-4 text-gray-700 dark:text-gray-400">
      <p>{{ props.message }}</p>
    </main>
    <footer class="flex justify-end gap-2 px-4 pb-2">
      <UIButton variant="neutral-light" class="!px-4 !text-sm" @click="handleCancel">
        {{ $t("cancel") }}
      </UIButton>
      <UIButton
        :variant="_confirmOptions.variant"
        class="!px-4 !text-sm"
        autofocus
        @click="handleConfirm"
      >
        {{ _confirmOptions.label }}
      </UIButton>
    </footer>
  </dialog>
</template>

<script setup>
const props = defineProps({
  title: {
    type: String,
    required: true,
  },
  message: {
    type: String,
    required: true,
  },
  confirmOptions: {
    type: Object,
    required: false,
    default: () => ({
      label: false,
      variant: false,
    }),
  },
  onConfirm: {
    type: Function,
    required: true,
  },
  onCancel: {
    type: Function,
    required: true,
  },
});

const { t: $t } = useI18n();

const _confirmOptions = computed(() => ({
  label: props.confirmOptions.label || $t("confirm"),
  variant: props.confirmOptions.variant || "success",
}));

const dialog = useTemplateRef("dialog");

function handleBackdropClick(event) {
  if (!dialog.value) return;

  const rect = dialog.value.getBoundingClientRect();
  const isInDialog =
    rect.top <= event.clientY &&
    event.clientY <= rect.top + rect.height &&
    rect.left <= event.clientX &&
    event.clientX <= rect.left + rect.width;

  if (!isInDialog) handleCancel();
}

function handleCancel() {
  if (!dialog.value) return;

  dialog.value.close();
  props.onCancel();
}

function handleConfirm() {
  dialog.value.close();
  props.onConfirm();
}

onMounted(() => {
  dialog.value.showModal();
});
</script>

<style lang="scss" scoped>
dialog[open] {
  animation: scale-up-center 0.3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-10-5 16:9:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@-webkit-keyframes scale-up-center {
  0% {
    opacity: 0.5;
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    opacity: 0.5;
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
