nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: 68DCA13C-6B01-4C55-B91D-D3C65EBE8592
  awesomeMe:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: 68DCA13C-6B01-4C55-B91D-D3C65EBE8592
